// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Fs = require("fs");
var Os = require("os");
var Curry = require("bs-platform/lib/js/curry.js");
var Belt_Array = require("bs-platform/lib/js/belt_Array.js");
var Caml_array = require("bs-platform/lib/js/caml_array.js");

var encoding = "utf8";

var getToday = (function() {
  let date = new Date();
  return new Date(date.getTime() - (date.getTimezoneOffset() * 60000))
    .toISOString()
    .split("T")[0];
});

var pendingTodosFile = "todo.txt";

var completedTodosFile = "done.txt";

var helpString = "Usage :-\n$ ./todo add \"todo item\"  # Add a new todo\n$ ./todo ls               # Show remaining todos\n$ ./todo del NUMBER       # Delete a todo\n$ ./todo done NUMBER      # Complete a todo\n$ ./todo help             # Show usage\n$ ./todo report           # Statistics";

function readFile(filename) {
  if (!Fs.existsSync(filename)) {
    return [];
  }
  var text = Fs.readFileSync(filename, {
        encoding: encoding,
        flag: "r"
      });
  return text.split("\n");
}

function appendToFile(filename, text) {
  Fs.appendFileSync(filename, text, {
        encoding: encoding,
        flag: "a+"
      });
  
}

function writeFile(filename, lines) {
  var text = lines.join(Os.EOL);
  Fs.writeFileSync(filename, text, {
        encoding: encoding,
        flag: "w"
      });
  
}

function updateFile(filename, updaterFn) {
  var contents = readFile(filename);
  var updatedContent = Curry._1(updaterFn, contents);
  return writeFile(filename, updatedContent);
}

function cmdHelp(param) {
  console.log(helpString);
  
}

function cmdLs(param) {
  var todos = readFile(pendingTodosFile);
  if (todos.length === 0) {
    console.log("There are no pending todos!");
    return ;
  }
  var length = todos.length;
  var formattedTodos = Belt_Array.reduceWithIndex(Belt_Array.reverse(todos), "", (function (acc, todo, index) {
          var todoIndex = length - index | 0;
          return acc + ("[" + todoIndex + "] " + todo + "\n");
        }));
  console.log(formattedTodos);
  
}

function cmdAddTodo(text) {
  if (text == null) {
    console.log("Error: Missing todo string. Nothing added!");
  } else {
    updateFile(pendingTodosFile, (function (todos) {
            return todos.concat([text]);
          }));
    console.log("Added todo: \"" + text + "\"");
  }
  
}

function cmdDelTodo(number) {
  if (number == null) {
    console.log("Error: Missing NUMBER for deleting todo.");
    return ;
  }
  var index = Number.parseInt(number);
  return updateFile(pendingTodosFile, (function (todos) {
                if (index < 1 || index > todos.length) {
                  console.log("Error: todo #" + index + " does not exist. Nothing deleted.");
                } else {
                  todos.splice(index, 1);
                  console.log("Deleted todo #" + number);
                }
                return todos;
              }));
}

function cmdMarkDone(number) {
  if (number == null) {
    console.log("Error: Missing NUMBER for marking todo as done.");
    return ;
  }
  var index = Number.parseInt(number);
  var todos = readFile(pendingTodosFile);
  if (index < 1 || index > todos.length) {
    console.log("Error: todo #" + number + " does not exist.");
    return ;
  }
  var completedTodo = todos.splice(index - 1 | 0, 1);
  writeFile(pendingTodosFile, todos);
  var completedTodoStr = "x " + Curry._1(getToday, undefined) + " " + Caml_array.get(completedTodo, 0) + "\n";
  appendToFile(completedTodosFile, completedTodoStr);
  console.log("Marked todo #" + index + " as done.");
  
}

function cmdReport(param) {
  var pending = readFile(pendingTodosFile).length;
  var completed = readFile(completedTodosFile).length - 1 | 0;
  console.log(Curry._1(getToday, undefined) + " Pending : " + String(pending) + " Completed : " + String(completed));
  
}

var args = process.argv;

var command = args.length >= 3 ? Caml_array.get(args, 2) : null;

var arg = args.length >= 4 ? Caml_array.get(args, 3) : null;

if (command == null) {
  console.log(helpString);
} else {
  switch (command) {
    case "add" :
        cmdAddTodo(arg);
        break;
    case "del" :
        cmdDelTodo(arg);
        break;
    case "done" :
        cmdMarkDone(arg);
        break;
    case "help" :
        console.log(helpString);
        break;
    case "ls" :
        cmdLs(undefined);
        break;
    case "report" :
        cmdReport(undefined);
        break;
    default:
      console.log(helpString);
  }
}

exports.encoding = encoding;
exports.getToday = getToday;
exports.pendingTodosFile = pendingTodosFile;
exports.completedTodosFile = completedTodosFile;
exports.helpString = helpString;
exports.readFile = readFile;
exports.appendToFile = appendToFile;
exports.writeFile = writeFile;
exports.updateFile = updateFile;
exports.cmdHelp = cmdHelp;
exports.cmdLs = cmdLs;
exports.cmdAddTodo = cmdAddTodo;
exports.cmdDelTodo = cmdDelTodo;
exports.cmdMarkDone = cmdMarkDone;
exports.cmdReport = cmdReport;
exports.args = args;
exports.command = command;
exports.arg = arg;
/* args Not a pure module */
